---
title: "Staff-Graded Time Series State-Space and Hidden Markov Models"
output: html_document
date: "2023-06-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(gridExtra)
library(xts)
library(depmixS4)
library(dlm)

DLM_data <- readr::read_csv('https://raw.githubusercontent.com/DapperDataAnalyst/Advanced_Predictive_Models/main/DLM_Data.csv')

```

### Part (a)

```{r message=FALSE, warning=FALSE}
Ft <- 1.2
Gt <- 0.8
m0 <- 0
C0 <- 25
sigma2nu <- 9
sigma2omega <- 4
n <- nrow(DLM_data)


DLM_model <- dlm(FF = Ft,
               GG = Gt,
               V = sigma2nu,
               W = sigma2omega,
               m0 = m0,
               C0 = C0) 

DLM_data_filtered <- dlmFilter(y = DLM_data$yt,
                               mod = DLM_model)


DLM_data$pred <- DLM_data_filtered$a
DLM_data$pSE <- sqrt(unlist(
  dlmSvd2var(DLM_data_filtered$U.R, 
             DLM_data_filtered$D.R)))


gg_DLM <- ggplot(DLM_data) +
  geom_line(aes(y = yt, x = time), 
            linetype = "dashed",
            color = "black") +
  geom_line(aes(y = pred, x = time),
            color = "red",
            size = 1.2) +
  geom_ribbon(aes(x = time, 
                  ymin = pred - 1.96 * pSE,
                  ymax = pred + 1.96 * pSE),
                  fill = "red",
              alpha = 0.2) +
  ylab(NULL) +
  theme_bw()


gg_DLM


a40 <- DLM_data$pred[40]
R40 <- DLM_data$pSE[40]^2

a40
R40

```

Using the process above, we find $a_{40} = `r a40`$ and $R_{40} = `r R40`$

### Part (b)

```{r}

DLM_data$ft <- DLM_data$pred * Ft

ggplot(DLM_data) +
  geom_line(aes(y = yt, x = time), 
            linetype = "dashed",
            color = "black") +
  geom_line(aes(y = ft, x = time),
            color = "blue",
            size = 1.2) +
  geom_ribbon(aes(x = time, 
                  ymin = pred - 1.96 * pSE,
                  ymax = pred + 1.96 * pSE),
                  fill = "blue",
              alpha = 0.2) +
  ylab(NULL) +
  theme_bw()

f40 <- Ft*a40
Q40 <- Ft*R40*t(Ft) + sigma2nu

f40
Q40[1]

```

### Part (c)

```{r}

DLM_data$filtered <- dropFirst(DLM_data_filtered$m)
DLM_data$fSE <- dropFirst(sqrt(unlist(
  dlmSvd2var(DLM_data_filtered$U.C, 
             DLM_data_filtered$D.C))))

ggplot(DLM_data) +
  geom_line(aes(y = yt, x = time), 
            linetype = "dashed",
            color = "black") +
  geom_line(aes(y = filtered, x = time),
            color = "green",
            size = 1.2) +
  geom_ribbon(aes(x = time, 
                  ymin = pred - 1.96 * fSE,
                  ymax = pred + 1.96 * fSE),
                  fill = "green",
              alpha = 0.2) +
  ylab(NULL) +
  theme_bw()


m40 <- DLM_data$filtered[40]
C40 <- DLM_data$fSE[40]^2

m40
C40

```

### Part (d)

We are given from the lecture notes that $a_t = E[ \theta_t | y_{1:(t-1)}] = G_t m_{t-1}$

We have found that $m_{22} = 3.539$ and we are given that $Gt = `r Gt`$.

We can use this information to "traverse" from $t = 22$ to $t = 30$ as follows:
$$\theta_{t+k} = G_t^k * m_t$$
$$\theta_{30} = G_t^{30-22} * m_{22}$$
$$= (0.8)^8 * 3.539 = 0.5937457$$









