---
title: "Time Series EDA and Classical Models"
output: html_document
date: "2023-06-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(gridExtra)
library(tidyverse)
library(astsa)
library(xts)
library(lubridate)

ARMAdata1 <- readr::read_csv('https://raw.githubusercontent.com/DapperDataAnalyst/Advanced_Predictive_Models/main/ARMAData1.csv')

ARMAdata2 <- readr::read_csv('https://raw.githubusercontent.com/DapperDataAnalyst/Advanced_Predictive_Models/main/ARMAData2.csv')

```

## Question 1
### Part (a)
```{r message=FALSE, warning=FALSE}


order_count <- 3
fit_objects <- matrix(rep(0,order_count), nrow = order_count, ncol = order_count)

for (p in 1:3){
  for (q in 1:3){
    fit <- sarima(ARMAdata1$x,
                  p = p, 
                  d = 0, 
                  q = q, 
                  no.constant = TRUE,
                  details = FALSE)
    
    fit_objects[p,q] <- fit$AICc
    
  }
}

fit_objects[2,2] <- 0 # Remove (p=2, q=2) case
fit_objects


```
From this analysis, ARMA(p=3, q=1) yields the lowest AICc value, and thus the best.


### Part (b)
```{r}
sarima(ARMAdata1$x,
                  p = 3, 
                  d = 0, 
                  q = 1, 
                  no.constant = TRUE,
                  details = FALSE)

```

From the output shown above, our ARMA model is as follows:
$$x_t = \phi_1 x_{t-1} + \phi_2 x_{t-2} + \phi_3 x_{t-3} + \theta_1 w_{t-1} + w_t$$
$$= 0.7996 x_{t-1} + 0.5480 x_{t-2} - 0.7759 x_{t-3} + 0.5535 w_{t-1} + w_t$$
Here, the estimated value of $\sigma^2_w = 1.028$

### Part (c)
```{r message=FALSE, warning=FALSE}
n_train = 150
ARMAdata2_train <- ARMAdata2[1:n_train,]

fit <- sarima(ARMAdata2$x,
                  p = 2, 
                  d = 0, 
                  q = 2, 
                  no.constant = TRUE,
                  details = FALSE)

fit


```
The resulting AICc value is `r fit$AICc`

### Part (d)
```{r}
fit_for <- sarima.for(ARMAdata2_train$x, 
                      n.ahead = nrow(ARMAdata2) - n_train, 
                      p = 2, 
                      d = 0, 
                      q = 2,
                      plot = F)






```
